# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d5b5125a7b0cc33198cf5424cf3d099d59a262a61f2937907068a592f0f5c390d7cfb76c836c4df80dfc77ffd2c9f65397fadf3af7b8a0b96b6f40d0dcbb5e

test:
  secret_key_base: 76117b2463523cde3c00fb6f583eda6c6e3ebbd4ee8865c2d1a4ae4883c96f9e431f11c302c7d74b5c4b6e419399976b2aec8c070f70a5f8e095cf1fe02ee5e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
